name: xopinionx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  build_runner: ^1.11.0
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.1
  device_preview: ^0.5.5
  equatable: ^1.2.5
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.1
  flutter_custom_clippers: ^1.1.2
  flutter_svg: ^0.19.2+1
  fluttertoast: ^7.1.6
  google_fonts: ^1.1.2
  google_sign_in: ^4.5.9
  http: ^0.12.2
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  logger: ^0.9.4
  provider: ^4.3.3
  pull_to_refresh: ^1.6.4
  responsive_builder: ^0.3.0
  responsive_framework: ^0.0.14
  dropdownfield: ^1.0.3
  flutter_chips_input: ^1.9.5
  lite_rolling_switch: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/images/home_page_images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
